### PR TITLE
Commandline options

### PR DESCRIPTION
**Pull request by budRich**
When I saw this tool (herbe) i instantly knew i wanted to try to get commandline options for it i always wanted this program on linux. I am not experienced with C programming, feel free to do and say what you want, but it would be really cool if we could get CLI options. I used the external library https://github.com/skeeto/optparse , because it looked like the easiest (and best?) implementation of a getopt function that supported both long and short options, author also wrote this: https://nullprogram.com/blog/2020/08/01/ ..

I also added more enums to "corner", which i think you should rename "anchor":  
```
123
456
789
```

Anyways, big thanks for your tool.

### CODE REVIEW

**Review by gitRaiku — CHANGES_REQUESTED** [review]
This looks really cool tho it would be nice to have a flag that makes the first line bolded and/or have with a bigger font

**Comment by dudik** [comment]
I appreciate your contributions, but I don't think it's the best time to make pull requests right now. I still make substantial changes to herbe nearly everyday. The code changes frequently and at the time you published this pull request, it was already a commit behind resulting in conflicts that have to be resolved. I will get back to this PR when I finish all the "main" functionality. I will mark that with a 1.0 release to signal the appropriate time to make PRs and patches. I hope that herbe won't change much after that point. Thank you.

**Comment by budRich** [comment]
Sounds good. I have some more things i want to try out and will do that on my fork, i make an issue next time !

**Comment by dudik** [comment]
The 1.0 release is out and as promised I'm coming back to this PR. I also saw your videos and now I understand why someone would benefit from command-line options in herbe. It also made me quite happy to literally hear your interest in herbe. You can now finally make a patch without much trouble. I would suggest splitting the patch into "cmd options" and "more anchors".

I was also thinking about creating my own, more minimal, patch for command-line options as I'm not a big fan of "unnecessary" external libraries and long options. But that's a big maybe, so feel free to get to work if you are still interested. And of course feel free to contact me if you want to collaborate or discuss anything about herbe. Thanks.

**Comment by budRich** [comment]
Cool, i will give it some bud this weekend. I completely understand you on the "no-external-lib" thing. And i don't think it will be difficult to replace the optionparsing functions with homebrew ones. But still, the library is quite compact and minimal and half of the headerfile could be removed i think since we are not using all of the functions here. 

Do you have any thoughts about "option-names", meaning is `-c` good for backgroundcolor, or should it be saved for a possible future shortoption for `--config-file` and stuff like that?

**Comment by dudik** [comment]
If we are talking about a patch, I don't really want to limit you in any way. A patch should be exactly as the author envisioned it, so if you want to use the external library or you want to support long options, feel free to do so. If someone doesn't like the patch for any reason, they can create their own. That's the beauty of it. And to be honest, I don't really have much thoughts about naming the cmd arguments. Maybe I'll add a `-v` flag for version or `-h` for help in the future, but that's it, at least for now.

**Pull request closed without merging**
