### PR TITLE
Fixed new line character still showing up.

### PR DESCRIPTION
**Pull request by OleStrohm**
Your previous patch correctly makes the line split on a literal new line, but it still drew the new line in addition to splitting the line. This patch overwrites the new line character with null character, stopping the drawing.

### CODE REVIEW

**Comment by dudik** [comment]
I'm not able to reproduce this bug. Can you send me an example command?

**Comment by OleStrohm** [comment]
herbe "first line\\
Second line\\
\\
Fourth line"

Gives square characters on the end of lines 1 through 3. It may be that your font has a proper invisible character for new lines? The sauare character showed up before this patch too, did they for you? I can send a screenshot if you want.

**Comment by dudik** [comment]
Could you specify the font you used?

Edit: I found a font that causes the same issue. I think I fixed it in the last commit. I didn't merge this PR because I explored the problem a little bit more and found a somewhat more efficient way to do it. Thank you for finding the bug and your contribution. I will close this issue if it also works on your end.

**Comment by OleStrohm** [comment]
That fixed it, but now you print a space at the end of each line. Won't that increase the effective length of that line? For example if the text part of the line is 47 pixels wide, and a space is 5 px, and the width of herbe is 50 px, then the last word will wrap? Or does X already have checks for this and stops the space from causing it to wrap?

**Comment by dudik** [comment]
It shouldn't matter as I'm replacing one character with another. I'm not adding anything. Overall I'm not really happy with the way the new line parsing "algorithm" is written, so I'll probably rework it in the future. But as long as it works, I'm closing this.

**Pull request closed without merging**
